### ISSUE TITLE
请问运行报错？

### ISSUE THREAD

**Issue by ylmyg** [chengzichen/Flyabbit#10]
Unable to find source java class: 'F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\src\main\independent\java\com.dhc.flyabbit.my\MyDebugActivity.java' because it does not belong to any of the source dirs: '[F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\src\main\java, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\src\debug\java, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\r\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\buildConfig\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\aidl\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\rs\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\kapt\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\kapt\debug, F:\YG\AllNetDemo2\View\Flyabbit\Flyabbit\my\build\generated\source\kapt\debug]'
感觉是这个类的问题 MyDebugActivity.java

**Comment by ylmyg** [comment]
我是运行 app出现的 运行 home 则是正常显示

**Comment by chengzichen** [comment]
有些时候是 AndroidStudio 缓存问题引起的,你可以尝试 clean app下工程,再次尝试
