### ISSUE TITLE
你好，现在能直接用了吗？

### ISSUE THREAD

**Issue by lmdiloveu** [chengzichen/Flyabbit#9]

**Comment by lmdiloveu** [comment]
主要是做组件化？

**Comment by lmdiloveu** [comment]
![image](https://user-images.githubusercontent.com/8290718/39740459-3ce87b64-52c8-11e8-9ab1-67211f8d4166.png)
一个项目是有这么多个主module的意思？没明白，需要了解哪一块的知识点才看明白你的项目代码结构？

**Comment by chengzichen** [comment]
现在工程一直在更新,可以以运行.

简单说下: 每个module是细分的功能模块,也都是可以单独运行,每个module的功能也可以组合起来成一个app,比如项目中的app模块,这样开放就类似拼积木一样,你可以先了解下组件化开发思想,这样可能比较容易看懂.该工程还包含了: MVP,插件化,RN等
